prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ENVO: <http://purl.obolibrary.org/obo/ENVO_>
select
?sub ?super
where
{
    ?sub rdfs:subClassOf ?super
    filter(isuri(?super))
    filter(isuri(?sub))
}
#limit 3
# also try a sco+ query?

